// Pavyzdys braižymui https://dbdiagram.io/d svetainėje

Table Skaitytojas {
    Note: "Bibliotekos lankytojas"
    ID int [pk, note: "Skaitytojo identifikatorius"]
    Name varchar [note: "Vardas"]
    Surname varchar [note: "Pavardė"]
    Phone varchar [note: "Telefonas"]
    Email varchar [note: "El. paštas"]
    Registration date [note: "Registracija"]
}

Table Knyga {
    Note: "Knygos duomenys, bendri jos egzemplioriams"
    ID int [pk, note: "Knygos identifikatorius"]
    ParentID int [ref: > Knyga.ID, note: "Viršesnis identifikatorius"]
    AuthorID int [ref: > Autorius.ID, note: "Autoriaus identifikatorius"]
    Title varchar [note: "Pavadinimas"]
    ISBN varchar [note: "ISBN kodas"]
    GenreID int [ref: > Žanras.ID, note: "Žanro identifikatorius"]
    PublisherID int [ref: > Leidėjas.ID, note: "Leidėjo identifikatorius"]
    Year int [note: "Leidimo metai"]
}

Table Išdavimas {
    Note: "Knygos paskolinimas skaitytojui"
    ID int [pk, note: "Išdavimo identifikatorius"]
    ClientID int [ref: > Skaitytojas.ID, note: "Skaitytojo identifikatorius"]
    BookCopyID int [ref: > "Knygos kopija".ID, note: "Knygos kopijos identifikatorius"]
    LibrarianID int [ref: > Bibliotekininkas.ID, note: "Bibliotekininko identifikatorius"]
    IssueDate date [note: "Išdavimo data"]
    ReturnDate date [note: "Grąžinimo data"]
}

Table Bibliotekininkas {
    Note: "Bibliotekos darbuotojas"
    ID int [pk, note: "Bibliotekininko identifikatorius"]
    Name varchar [note: "Vardas"]
    Surname varchar [note: "Pavardė"]
    Phone varchar [note: "Telefonas"]
    Email varchar [note: "El. paštas"]
    EmploymentDate date [note: "Įdarbinimo data"]
}

Table Atsiliepimas {
    Note: "Skaitytojo atsiliepimas apie knygą"
    ID int [pk, note: "Atsiliepimo identifikatorius"]
    ClientID int [ref: > Skaitytojas.ID, note: "Skaitytojo identifikatorius"]
    BookID int [ref: > Knyga.ID, note: "Knygos identifikatorius"]
    Date date [note: "Parašymo data"]
    Review text [note: "Atsiliepimo turinys"]
}

Table Autorius {
    Note: "Rašytojas arba leidinio sudarytojas"
    ID int [pk, note: "Autoriaus identifikatorius"]
    Name varchar [note: "Vardas"]
    Surname varchar [note: "Pavardė"]
    Biography text [note: "Biografija"]
}

Table Leidėjas {
    Note: "Leidykla, institucija arba organizacija"
    ID int [pk, note: "Leidėjo identifikatorius"]
    Name varchar [note: "Pavadinimas"]
    Address varchar [note: "Adresas"]
    Phone varchar [note: "Telefonas"]
}

Table Žanras {
    Note: "Knygos teminė grupė"
    ID int [pk, note: "Žanro identifikatorius"]
    Name varchar [note: "Žanro pavadinimas"]
}

Table "Knygos kopija" {
    Note: "Vienodų knygų egzemplioriai"
    ID int [pk, note: "Kopijos identifikatorius"]
    BookID int [ref: > Knyga.ID, note: "Knygos identifikatorius"]
    Status varchar [note: "Būsena"]
}

Table Rezervacija {
    Note: "Išankstinis knygų užsakymas"
    ID int [pk, note: "Rezervacijos identifikatorius"]
    ClientID int [ref: > Skaitytojas.ID, note: "Skaitytojo identifikatorius"]
    BookCopyID int [ref: > "Knygos kopija".ID, note: "Knygos kopijos identifikatorius"]
    ReservationDate date [note: "Rezervacijos data"]
    ExpirationDate date [note: "Pabaigos data"]
}
